//! VTK/Common/Core translation targets.
pub(crate) mod abstract_array;
pub mod animation_cue;
pub mod any_array;
pub mod archiver;
pub mod array_components;
pub mod array_coordinates;
pub mod array_extents;
pub mod array_extents_list;
pub mod array_iterator;
pub mod array_range;
pub mod array_sort;
pub mod array_weights;
pub mod atomic_mutex;
pub mod batch;
pub mod bit_array;
pub mod box_mueller_random_sequence;
pub mod break_point;
pub mod byte_swap;
pub mod callback_command;
pub mod char_array;
pub mod collection;
pub mod collection_iterator;
pub mod command;
pub mod common_information_key_manager;
pub mod constant_array;
pub mod data_array;
pub mod data_array_collection;
pub mod data_array_collection_iterator;
pub mod data_array_selection;
pub mod debug_leaks_manager;
pub mod double_array;
pub mod dynamic_loader;
pub mod event_forwarder_command;
pub mod file_output_window;
pub mod float_array;
pub mod floating_point_exceptions;
pub mod garbage_collector_manager;
pub mod gaussian_random_sequence;
pub mod hash_combiner;
pub mod id_list;
pub mod id_list_collection;
pub mod id_type_array;
pub mod indent;
pub mod information;
pub mod information_data_object_key;
pub mod information_double_key;
pub mod information_double_vector_key;
pub mod information_id_type_key;
pub mod information_information_key;
pub mod information_information_vector_key;
pub mod information_integer_key;
pub mod information_integer_pointer_key;
pub mod information_integer_vector_key;
pub mod information_iterator;
pub mod information_key;
pub mod information_key_lookup;
pub mod information_key_vector_key;
pub mod information_object_base_key;
pub mod information_object_base_vector_key;
pub mod information_request_key;
pub mod information_string_key;
pub mod information_string_vector_key;
pub mod information_unsigned_long_key;
pub mod information_variant_key;
pub mod information_variant_vector_key;
pub mod information_vector;
pub mod int_array;
pub mod large_integer;
pub mod long_array;
pub mod long_long_array;
pub mod math;
pub mod minimal_standard_random_sequence;
pub mod number_to_string;
pub mod o_str_stream_wrapper;
pub mod object;
pub mod object_base;
pub mod object_base_handle;
pub mod object_factory_collection;
pub mod old_style_callback_command;
pub mod output_window;
pub mod override_attribute;
pub mod override_information;
pub mod override_information_collection;
pub mod points;
pub mod points_2d;
pub mod priority_queue;
pub mod random_pool;
pub mod random_sequence;
pub mod reference_count;
pub mod short_array;
pub mod signed_char_array;
pub mod smart_pointer_base;
pub mod smp_tools;
pub mod std_string;
pub mod string_array;
pub mod string_output_window;
pub mod string_token;
pub mod structured_point_array;
pub mod time_point_utility;
pub mod time_stamp;
pub mod unsigned_char_array;
pub mod unsigned_int_array;
pub mod unsigned_long_array;
pub mod unsigned_long_long_array;
pub mod unsigned_short_array;
pub mod value_from_string;
pub mod version;
pub mod void_array;
pub mod vtk_type;
pub mod weak_pointer_base;
pub mod weak_reference;
pub mod window;
pub mod xml_file_output_window;

pub use animation_cue::{
    AnimationCue, AnimationCueInfo, PlayDirection, TIMEMODE_NORMALIZED, TIMEMODE_RELATIVE,
};
pub use any_array::AnyArray;
pub(crate) use any_array::ArrayError;
pub use archiver::Archiver;
pub use array_components::{
    array_components, component_or_norm_as_array, component_or_norm_as_data_array, to_enumerant,
    to_string, VtkArrayComponents,
};
pub use array_coordinates::{ArrayCoordinates, CoordinateT, DimensionT};
pub use array_extents::{ArrayExtents, SizeT};
pub use array_extents_list::ArrayExtentsList;
pub use array_iterator::{ArrayIterator, ArrayIteratorArray, ArrayIteratorTemplate};
pub use array_range::ArrayRange;
pub use array_sort::ArraySort;
pub use array_weights::ArrayWeights;
pub use atomic_mutex::AtomicMutex;
pub use batch::{Batch, Batches};
pub use bit_array::BitArray;
pub use box_mueller_random_sequence::BoxMuellerRandomSequence;
pub use break_point::BreakPoint;
pub use byte_swap::{ByteSwap, ByteSwapValue};
pub use callback_command::{CallbackCommand, CallbackCommandCallback, ClientDataDeleteCallback};
pub use char_array::CharArray;
pub use collection::{Collection, CollectionSimpleIterator};
pub use collection_iterator::CollectionIterator;
pub use command::{Command, EventId};
pub use common_information_key_manager::CommonInformationKeyManager;
pub use constant_array::{ConstantArray, IntConstantArray, UnsignedCharConstantArray};
pub use data_array_collection::DataArrayCollection;
pub use data_array_collection_iterator::DataArrayCollectionIterator;
pub use data_array_selection::DataArraySelection;
pub use debug_leaks_manager::DebugLeaksManager;
pub use double_array::DoubleArray;
pub use dynamic_loader::{DynamicLoader, VtkLibHandle, VtkSymbolPointer};
pub use event_forwarder_command::EventForwarderCommand;
pub use file_output_window::FileOutputWindow;
pub use float_array::FloatArray;
pub use floating_point_exceptions::FloatingPointExceptions;
pub use garbage_collector_manager::GarbageCollectorManager;
pub use gaussian_random_sequence::GaussianRandomSequence;
pub use hash_combiner::HashCombiner;
pub use id_list::{DeleteMethod, IdList};
pub use id_list_collection::IdListCollection;
pub use id_type_array::IdTypeArray;
pub use indent::{Indent, VTK_NUMBER_OF_BLANKS, VTK_STD_INDENT};
pub use information::{Information, InformationHandle};
pub use information_data_object_key::InformationDataObjectKey;
pub use information_double_key::InformationDoubleKey;
pub use information_double_vector_key::InformationDoubleVectorKey;
pub use information_id_type_key::InformationIdTypeKey;
pub use information_information_key::InformationInformationKey;
pub use information_information_vector_key::InformationInformationVectorKey;
pub use information_integer_key::InformationIntegerKey;
pub use information_integer_pointer_key::InformationIntegerPointerKey;
pub use information_integer_vector_key::InformationIntegerVectorKey;
pub use information_iterator::InformationIterator;
pub use information_key::InformationKey;
pub use information_key_lookup::InformationKeyLookup;
pub use information_key_vector_key::InformationKeyVectorKey;
pub use information_object_base_key::InformationObjectBaseKey;
pub use information_object_base_vector_key::InformationObjectBaseVectorKey;
pub use information_request_key::InformationRequestKey;
pub use information_string_key::InformationStringKey;
pub use information_string_vector_key::InformationStringVectorKey;
pub use information_unsigned_long_key::InformationUnsignedLongKey;
pub use information_variant_key::InformationVariantKey;
pub use information_variant_vector_key::InformationVariantVectorKey;
pub use information_vector::{InformationVector, InformationVectorHandle};
pub use int_array::IntArray;
pub use large_integer::LargeInteger;
pub use long_array::LongArray;
pub use long_long_array::LongLongArray;
pub use minimal_standard_random_sequence::MinimalStandardRandomSequence;
pub use number_to_string::{Notation, NumberToString, NumberToStringValue, TagDouble, TagFloat};
pub use o_str_stream_wrapper::OStrStreamWrapper;
pub use object::Object;
pub use object_base::ObjectBase;
pub(crate) use object_base::WeakPointerSlot;
pub use object_base_handle::{ObjectBaseApi, ObjectBaseHandle};
pub use object_factory_collection::ObjectFactoryCollection;
pub use old_style_callback_command::{OldStyleCallback, OldStyleCallbackCommand};
pub use output_window::{
    vtk_output_window_display_debug_text, vtk_output_window_display_error_text,
    vtk_output_window_display_generic_warning_text, vtk_output_window_display_text,
    vtk_output_window_display_warning_text, DisplayMode, OutputWindow,
};
pub use override_attribute::OverrideAttribute;
pub use override_information::{ObjectFactoryHandle, OverrideInformation};
pub use override_information_collection::OverrideInformationCollection;
pub use points::{Points, VTK_DOUBLE, VTK_FLOAT};
pub use points_2d::Points2D;
pub use priority_queue::{PriorityQueue, PriorityQueueItem, VTK_DOUBLE_MAX};
pub use random_pool::RandomPool;
pub use random_sequence::RandomSequence;
pub use reference_count::ReferenceCount;
pub use short_array::ShortArray;
pub use signed_char_array::SignedCharArray;
pub use smart_pointer_base::SmartPointerBase;
pub use smp_tools::{SmpTools, SmpToolsConfig};
pub use std_string::StdString;
pub use string_array::StringArray;
pub use string_output_window::StringOutputWindow;
pub use string_token::{StringToken, StringTokenHash, INVALID_HASH};
pub use structured_point_array::{StructuredPointArray, StructuredPointBackend};
pub use time_point_utility::TimePointUtility;
pub use time_stamp::TimeStamp;
pub use unsigned_char_array::UnsignedCharArray;
pub use unsigned_int_array::UnsignedIntArray;
pub use unsigned_long_array::UnsignedLongArray;
pub use unsigned_long_long_array::UnsignedLongLongArray;
pub use unsigned_short_array::UnsignedShortArray;
pub use value_from_string::{vtk_value_from_string, VtkValueFromString};
pub use variant_array::{Variant, VariantArray};
pub use version::{
    get_vtk_version, vtk_version_check, Version, VTK_BUILD_VERSION, VTK_EPOCH_VERSION,
    VTK_MAJOR_VERSION, VTK_MINOR_VERSION, VTK_SOURCE_VERSION, VTK_VERSION, VTK_VERSION_FULL,
    VTK_VERSION_NUMBER, VTK_VERSION_NUMBER_QUICK,
};
pub use void_array::VoidArray;
pub use vtk_type::{
    VtkChar, VtkDataType, VtkIdType, VtkLong, VtkMTimeType, VtkTypeUInt32, VtkTypeUInt64,
    VtkUnsignedLong,
};
pub use weak_pointer_base::WeakPointerBase;
pub use weak_reference::WeakReference;
pub use window::{
    Window, VTK_CURSOR_ARROW, VTK_CURSOR_CROSSHAIR, VTK_CURSOR_CUSTOM, VTK_CURSOR_DEFAULT,
    VTK_CURSOR_HAND, VTK_CURSOR_SIZEALL, VTK_CURSOR_SIZENE, VTK_CURSOR_SIZENS, VTK_CURSOR_SIZENW,
    VTK_CURSOR_SIZESE, VTK_CURSOR_SIZESW, VTK_CURSOR_SIZEWE,
};
pub use xml_file_output_window::XMLFileOutputWindow;
pub mod variant_array;
